### ISSUE TITLE
Sqrt on GopherJS

### ISSUE THREAD

**Issue by EtienneBruines** [luxengine/math#1]
Hi!

I would like to report this error message (runtime, when actually calling `math.Sqrt`) on GopherJS:

```
native function not implemented: github.com/luxengine/math.Sqrt
```

I think this has to do with the fact that there's no implementation for netgo/GopherJS, and that Go doesn't know that `sqrt` can be used if `Sqrt` isn't available. As with all the previous crazy build problems: I don't really know how it works, but I do tend to find the errors.

**Comment by hydroflame** [comment]
Fixed
